export const questionBank = {
  love: [
    "Is it possible to truly love someone without fully understanding them?",
    "Can you be in love with two people at the same time, or is one just a mirror of what you're missing?",
    "If love fades, was it ever real — or was it always something else wearing love's face?",
    "Would you rather be deeply loved but never understood, or perfectly understood but never loved?",
    "Do we fall in love with people, or with the version of ourselves we become around them?",
    "If you could erase the memory of your greatest heartbreak, would you also lose the growth it gave you?",
    "Is vulnerability the bravest form of love, or the most dangerous?",
    "Can you love someone and still choose to walk away — and if so, what does that say about love?",
    "Does true love require sacrifice, or does sacrifice slowly corrupt what love is supposed to be?",
    "If you knew a relationship had an expiration date, would you still fall in love?",
    "Is the love you give a reflection of who you are, or who you wish to become?",
    "Do soulmates exist, or do we just choose someone and build the 'meant to be' story afterwards?",
    "What if the person you're meant to be with is someone you've already met and let go?",
    "Can two people be perfect for each other but still be wrong for each other at the same time?",
    "Is loving yourself a prerequisite for loving someone else, or can love from another teach you to love yourself first?",
    "What does it mean to love someone unconditionally when every human has conditions?",
    "If your partner could hear every thought you had about them, would the love survive?",
    "Is there a difference between loving someone and needing them — and does it matter?",
    "Would you rather have a love story that burns intensely for three years or gently for thirty?",
    "Is heartbreak proof that love was real, or just evidence of attachment?",
    "Can someone who has never been loved properly learn to love without reproducing the wound?",
    "Do we choose who we fall in love with, or does something deeper choose for us?",
    "Is the fear of being loved as powerful as the fear of never being loved at all?",
    "What would love look like if it had no biological purpose — if it existed purely as spirit?",
    "Is it more loving to tell someone the truth that hurts them, or the lie that protects them?",
    "Can you fully love someone you've never argued with?",
    "Is nostalgia for a past relationship love, or grief wearing love's costume?",
    "What if the reason you can't find love is because you don't believe you deserve to be found?",
    "If love is a choice, does it become less romantic — or more meaningful?",
    "Can love that began as lust ever become something truly deep and sacred?",
    "Is loneliness the absence of love, or the absence of someone who truly sees you?",
    "What's the difference between loving someone and being addicted to how they make you feel?",
    "If your younger self saw the relationships you've chosen, what would they think?",
    "Do you love people because of who they are, or because of how they make you feel about yourself?",
    "Is the love you show others a mirror of the love you secretly crave for yourself?",
    "Can love survive the moment when you see someone completely — flaws, fears, and shadows?",
    "What if the deepest form of love is the one that sets you free rather than holds you close?",
    "Is it possible to love someone too much — and if so, what does 'too much' actually destroy?",
    "If you stripped away physical attraction, shared memories, and social validation — would your love still stand?",
    "What does it feel like to love someone who will never love you back — and why do we keep doing it?",
  ],

  life: [
    "If you could see a timeline of your life from birth to death, would you actually want to watch it?",
    "Are the best years of your life happening right now, and you just can't see it yet?",
    "If every person you've ever met forgot you tomorrow, who would you still be?",
    "Is the life you're living the one you chose, or the one that happened while you were making other plans?",
    "What would you attempt if you knew failure was just a stepping stone, not an endpoint?",
    "If time stopped for everyone except you, what would you finally do?",
    "Are you living, or are you just not dying?",
    "What story will your life tell when read by someone a hundred years from now?",
    "If happiness is a state of mind, why do we keep chasing external things to find it?",
    "Is the meaning of life something you discover, or something you create?",
    "What are you putting off that you know, deep down, matters more than anything on your schedule?",
    "If you could send a one-sentence message to yourself five years ago, what would it be?",
    "What is the one thing you would do differently if no one was watching and no one was judging?",
    "If regret is the compass that reveals what you truly value, what has yours been pointing to?",
    "Are the beliefs you hold about yourself actually yours, or were they handed to you by someone else?",
    "What version of yourself died so that the current version could be born?",
    "Is the life you've built an expression of your soul, or an apology for existing?",
    "What would you do on your last Monday morning that you're not doing on this one?",
    "When you're old and looking back, will you regret the risks you took — or the ones you didn't?",
    "If life is finite, is anything truly urgent — or is everything equally trivial?",
    "Are you the author of your life, or a character reacting to events written by someone else?",
    "What would you need to unlearn to become the person you actually want to be?",
    "Is living simply the bravest or the most defeated thing a person can do?",
    "What does your daily routine say about what you actually value versus what you claim to value?",
    "If you could compress all your years into one single feeling, what emotion would summarize your life so far?",
    "What would your life look like if you stopped outsourcing your happiness to future events?",
    "Is there a version of your life running parallel to this one that you secretly grieve for?",
    "What has living taught you that no book, school, or person ever could?",
    "When did you last do something purely for the joy of doing it — not for validation or reward?",
    "If your life had a soundtrack, what song would be playing right now — and does it match the mood you want?",
    "What are you tolerating in your life that you've convinced yourself you have no choice about?",
    "Is the person you are at 3am closer to your true self than the person you present at noon?",
    "What would your life feel like if you stopped explaining yourself to people who never really listened?",
    "Are you building a life, or have you been building an escape route from one?",
    "If you could live one week of your life in slow motion, which week would you choose?",
    "What would change if you treated every day as though it were simultaneously your first and your last?",
    "Is your life a product of your choices, your circumstances, or your imagination of both?",
    "What would the most alive version of you look like — and what's stopping you from becoming that?",
    "If your fears and your dreams swapped places, what would you do tomorrow morning?",
    "What is the cost of the life you're not living?",
  ],

  existential: [
    "If we're living in a simulation, does it matter — and would you want to know?",
    "Does free will actually exist, or are we just biological algorithms running predetermined code?",
    "If you could know the answer to any one question about the universe, what would you ask?",
    "What if the purpose of life is not to find meaning, but to accept that there might be none?",
    "If consciousness can exist without a body, are 'you' really your body at all?",
    "Is death the end of consciousness, or the beginning of something we can't comprehend?",
    "If the universe has no obligation to make sense to you, how do you make peace with the chaos?",
    "If every atom in your body is replaced over seven years, are you the same person you were a decade ago?",
    "What if déjà vu is a glitch in the fabric of spacetime — a memory from a loop you've already lived?",
    "Is the self an illusion constructed by the brain to give continuity to a stream of disconnected moments?",
    "If there are infinite parallel universes, does your choice in this one actually matter at all?",
    "What would it mean to truly exist — to be here — rather than simply to appear to be?",
    "Is time something the universe experiences, or just something humans invented to cope with change?",
    "If you could peer behind the curtain of reality itself, would you be brave enough to look?",
    "Can something come from nothing, or has existence always been — and what does that say about beginnings?",
    "Is awareness itself proof that the universe is conscious, or just a local anomaly in dead matter?",
    "What if death is not an ending but a transition between forms of information?",
    "If the Big Bang was the beginning of everything, what existed in the silence before the first moment?",
    "Are emotions real — or just neurochemical narratives we tell ourselves to justify being alive?",
    "What if reality is not a shared experience but millions of private ones with no common ground?",
    "Is human consciousness the universe experiencing itself — or just an accident of biology?",
    "If language shapes thought, are there truths that humans will never be able to think?",
    "What would it mean for the universe to have a purpose — and who or what would be the purpose-giver?",
    "Is nothingness even possible — or does the concept of 'nothing' require something to define it against?",
    "What if enlightenment is not a state of knowing more, but a state of being disturbed by less?",
    "If every version of you that ever existed or will ever exist all happened simultaneously, who are you really?",
    "Is the present moment the only real thing — or is it simply the boundary between two illusions?",
    "What if the search for meaning is itself a defense mechanism against accepting a meaningless cosmos?",
    "Does the universe care about beauty — or did evolution simply wire us to find certain things beautiful?",
    "If we are all connected at the quantum level, where does one consciousness end and another begin?",
    "What if the things we fear most are just the edges of who we haven't yet become?",
    "Is suffering the price of consciousness — and if you could opt out, would you?",
    "What if every decision you've never made still exists somewhere, being lived by a version of you?",
    "Is reality what exists when no one is observing it — or does observation create reality?",
    "If the human lifespan were ten thousand years, would wisdom grow — or just regret?",
    "What would it mean to know everything — and would omniscience destroy the will to live?",
    "Is a universe without observers the same as a universe that doesn't exist?",
    "What if the question itself — not the answer — is the highest form of intelligence?",
    "If time is a river, are we swimming through it or is it flowing through us?",
    "What if the feeling that something is missing is not a flaw — but the very nature of being human?",
  ],

  success: [
    "If society stopped measuring success by wealth, would you still chase what you're chasing?",
    "What does your ideal life look like when no one is watching or judging?",
    "Are you building a life, or are you building a résumé?",
    "If you achieved everything you ever wanted tomorrow, what would you do the day after?",
    "Is your ambition driven by passion, or by a fear of being ordinary?",
    "What would you do if you had all the money you needed and no one to impress?",
    "Is the grind culture actually moving you forward, or keeping you too busy to think?",
    "What if your greatest failure is actually the redirection you needed?",
    "Are you comparing your chapter one to someone else's chapter twenty?",
    "If success means different things to every person, why do we follow the same path?",
    "What would 'enough' look like for you — and would you actually stop there?",
    "Is the person you're becoming worth what you're giving up to get there?",
    "What is the difference between ambition and desperation — and which one is driving you?",
    "If you could no longer post your wins publicly, would you still feel successful?",
    "Are you pursuing the life you want, or the life you think you're supposed to want?",
    "What does it cost you — in time, energy, relationships — to chase the success you're after?",
    "Is the version of success you're running toward actually yours, or did someone else plant it in you?",
    "What would you create if you knew it would never make you famous?",
    "Do you define yourself by what you achieve, or by who you become in the pursuit?",
    "If you stripped away your title, your income, and your social media — who are you?",
    "What if slowing down isn't falling behind — but the only way to truly arrive somewhere?",
    "Is excellence something you reach, or something you practice daily with no finish line?",
    "What have you sacrificed on the altar of success that you quietly wish you could get back?",
    "Are you moving toward something meaningful, or just running away from feeling like a failure?",
    "What would your work look like if you did it purely as a gift to the world, with no expectation of reward?",
    "Is the discipline you admire in others something they enjoy — or something they can't stop?",
    "What version of success did your parents have in mind for you, and how much has that shaped your choices?",
    "If you could only be remembered for one thing you built, what would you want it to be?",
    "What are you quietly jealous of — and what does that envy reveal about your unmet desires?",
    "Is being busy the same as being productive, or is it just a convincing performance of purpose?",
    "What would you do differently if you believed you were already enough, exactly as you are?",
    "Is there a dream you've been protecting by never pursuing it — so it can never disappoint you?",
    "What is the story you tell yourself about why you haven't started yet?",
    "If failure wasn't permanent, what would you risk right now?",
    "Are you the kind of successful that the ten-year-old version of you would be proud of?",
    "What would your life feel like if you measured progress by depth instead of speed?",
    "Is the goalpost you're running toward something you set — or something someone else handed you?",
    "What would you stop doing immediately if you were completely honest about whether it was working?",
    "Do you fear failure — or do you secretly fear what success would demand of you?",
    "What if the most successful thing you ever do is become someone who no longer needs validation to feel worthy?",
  ],

  dark: [
    "If you could witness the exact moment the universe ends, would you want to be there?",
    "What thought have you had that you've never told anyone — not because it's wrong, but because it's too real?",
    "If you knew you only had 24 hours left, would you finally be honest with everyone?",
    "Is there a part of you that no one has ever seen, and does it frighten you?",
    "What would happen if everyone could read your thoughts for just one minute?",
    "Are the things that keep you up at night the most honest conversations you have with yourself?",
    "What haunts you more: the things you've done, or the things you never had the courage to do?",
    "If every lie you've ever told suddenly became the truth, what would your reality look like?",
    "Is the darkness within you something to fight, or something to finally understand?",
    "What if the void doesn't stare back — what if it simply reflects what you're already carrying?",
    "If you could forget one thing permanently, what would it be — and what does your answer reveal?",
    "What would your life look like if you stopped running from the things that scare you most?",
    "Is there a version of you that could have become someone you'd be afraid to meet?",
    "What if the cruelest thing you've ever thought revealed more truth about the world than kindness does?",
    "Do you believe people are fundamentally good — or do you believe that because it's comforting?",
    "What if the thing you hate most in others is the thing you're most terrified to find in yourself?",
    "Is there a wound in you that you've stopped trying to heal because it's become part of your identity?",
    "What would you confess if you were guaranteed that no one would judge you, leave you, or remember it?",
    "Is loneliness the proof that we are separate beings — or evidence that we were never meant to be?",
    "What if the greatest act of self-destruction isn't suicide, but slowly choosing a life that deadens you?",
    "Do you secretly believe you deserve to suffer — and where did that belief first come from?",
    "What is the darkest corner of your mind that you've never shown anyone — including yourself?",
    "If your shadow self had a voice, what would it say to the face you show the world?",
    "What if every person who has hurt you was simply a broken mirror, and you just happened to be in the reflection?",
    "Is the numbness you feel sometimes a protection or a punishment?",
    "What would happen to your life if you stopped pretending to be okay in ways you're not?",
    "Do you grieve for the person you used to be — or the person you might have become?",
    "What is the one truth you've been telling yourself is too dark to ever speak out loud?",
    "If your fears could speak, what would they say they're trying to protect you from?",
    "Is the version of you that shows up at 3am more honest than the one that shows up at noon?",
    "What if the things you've survived didn't make you stronger — they just made you harder?",
    "Is there something broken in you that you've given up fixing — and chosen to simply live around?",
    "What would happen if you stopped carrying the guilt of things that were never your fault?",
    "If you could see the exact moment something inside you changed forever, would you recognize it?",
    "What does your anger want you to know that your politeness has been silencing?",
    "Is the mask you wear so convincing that you've forgotten it's a mask at all?",
    "What if healing isn't about going back to who you were — but grieving who you'll never be?",
    "Do you love yourself most on the days when you feel the least worthy of love?",
    "What if the heaviest thing you're carrying isn't your past — but the future you're afraid to lose?",
    "Is there a version of the story of your life that, if you told it differently, would set you free?",
  ],
};

const usedQuestions = {
  love: new Set(),
  life: new Set(),
  existential: new Set(),
  success: new Set(),
  dark: new Set(),
};

export function getRandomQuestion(category) {
  const categories = Object.keys(questionBank);
  const cat = category && questionBank[category] ? category : categories[Math.floor(Math.random() * categories.length)];
  const questions = questionBank[cat];

  // Reset if all used
  if (usedQuestions[cat].size >= questions.length) {
    usedQuestions[cat].clear();
  }

  const unused = questions.filter((_, i) => !usedQuestions[cat].has(i));
  const idx = questions.indexOf(unused[Math.floor(Math.random() * unused.length)]);
  usedQuestions[cat].add(idx);

  return {
    text: questions[idx],
    category: cat,
  };
}

export const dailyQuestionPool = [
  "If you could relive one moment in your life forever, which would it be — and would it still feel meaningful the hundredth time?",
  "What truth about yourself have you been avoiding because accepting it would change everything?",
  "If the universe is indifferent to your existence, does that make your choices more meaningful or less?",
  "What would you do differently if you knew no one would ever judge you?",
  "Is the person you are today someone your childhood self would recognize — and would they be proud?",
  "What are you holding onto that's actually holding you back from becoming who you need to be?",
  "If consciousness is just neurons firing, does love become less real — or more miraculous?",
  "What question are you most afraid to answer honestly, and why does it scare you so much?",
  "If you had to choose between knowing the date of your death or the manner, which would haunt you less?",
  "What would it take for you to feel truly free — not just content, but actually free?",
  "What part of yourself have you been apologizing for that actually deserves to be celebrated?",
  "If the version of you from five years ago could see you now, what would surprise them most?",
  "Is there a dream you gave up on that still visits you in quiet moments?",
  "What do you need to forgive yourself for before you can truly move forward?",
  "If today were the last ordinary day before everything changed, how would you spend it?",
  "What is the most honest conversation you've never had — and who should you have it with?",
  "Are you living in alignment with your values, or have you been quietly compromising them for comfort?",
  "What would your life feel like if fear no longer had a vote in your decisions?",
  "What has silence taught you that words never could?",
  "If love is the answer, have you been asking the right question?",
  "What is the bravest thing you could do tomorrow morning — and what stops you from doing it today?",
  "Is the story you tell about your past freeing you or quietly imprisoning you?",
  "What would change if you truly believed the universe was on your side?",
  "If your body could speak to you right now, what do you think it would say?",
  "What are you creating, and does it reflect the best version of who you are?",
  "If gratitude were a practice rather than a feeling, what would you choose to be grateful for right now?",
  "What is the one conversation that, if you had it, would change the trajectory of your life?",
  "Are you running toward something, or away from something — and do you know the difference?",
  "What would you build if you stopped waiting for permission?",
  "If your deepest self could send you a letter right now, what do you think it would say?",
  "What is the version of your life that exists just beyond the edge of your comfort zone?",
  "What have you been postponing that you know, in your bones, cannot wait forever?",
];
